// app/layout.tsx
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body className='bg-black'>
        {/* Wrapper container biar responsive */}
        <div className='w-full max-w-[1440px] mx-auto'>{children}</div>
      </body>
    </html>
  );
}
